from pathlib import Path


ROOT = Path(__file__).resolve().parent
INPUT_DIR = ROOT / "input_data"
RAW_DIR = INPUT_DIR / "raw"
PREPARED_DIR = INPUT_DIR / "prepared"
WORK_DIR = INPUT_DIR / "work"
WORK_SKIM_DIR = WORK_DIR / "skims"
WORK_GTFS_DIR = WORK_DIR / "gtfs"
SKIM_DIR = WORK_SKIM_DIR
OUTPUT_DIR = ROOT / "outputs"

ZONES_FILE = PREPARED_DIR / "zones.parquet"
DEMAND_PACKAGE_FILE = PREPARED_DIR / "demand.pkl.gz"
SKIM_PACKAGE_FILE = PREPARED_DIR / "skims.pkl.gz"
LOOKUP_PACKAGE_FILE = PREPARED_DIR / "lookups.pkl.gz"
ASSIGNMENT_NETWORK_FILE = PREPARED_DIR / "assignment_network.pkl"

RAW_NPVM_DIR = RAW_DIR / "npvm"
NPVM_ZONES_ARCHIVE = RAW_NPVM_DIR / "npvm_zones_2023.zip"
NPVM_ROAD_DEMAND_ARCHIVE = RAW_NPVM_DIR / "npvm_road_demand_2023.zip"
NPVM_PT_DEMAND_ARCHIVE = RAW_NPVM_DIR / "npvm_pt_demand_2023.zip"
NPVM_ACTIVE_DEMAND_ARCHIVE = RAW_NPVM_DIR / "npvm_active_demand_2023.zip"
EXTERNAL_BACKGROUND_GATEWAYS_FILE = RAW_NPVM_DIR / "external_road_background_gateways.csv"

RAW_BOUNDARY_DIR = RAW_DIR / "boundaries"
MUNICIPAL_BOUNDARIES_ARCHIVE = RAW_BOUNDARY_DIR / "canton_municipalities.zip"
QUARTIER_BOUNDARIES_ARCHIVE = RAW_BOUNDARY_DIR / "city_quartiers.zip"
NETWORK_POLICY_CITY_FILE = RAW_BOUNDARY_DIR / "zurich_city_boundary.parquet"

RAW_POPULATION_DIR = RAW_DIR / "population"
STATPOP_ARCHIVE = RAW_POPULATION_DIR / "statpop_2024.zip"
STATENT_ARCHIVE = RAW_POPULATION_DIR / "statent_2023.zip"

GTFS_FILE = RAW_DIR / "gtfs" / "gtfs_fp2026_20260422.zip"
RAW_OSM_DIR = RAW_DIR / "osm"
ROAD_GRAPH_FILE = RAW_OSM_DIR / "osm_drive.pkl"
WALK_GRAPH_FILE = RAW_OSM_DIR / "osm_walk.pkl"
BIKE_GRAPH_FILE = RAW_OSM_DIR / "osm_bike.pkl"
PT_ACCESS_WALK_GRAPH_FILE = RAW_OSM_DIR / "pt_access_walk.pkl"
PT_ACCESS_BIKE_GRAPH_FILE = RAW_OSM_DIR / "pt_access_bike.pkl"
BASE_NETWORK_FILE = RAW_OSM_DIR / "network_base.pkl"

MODE_CHOICE_FILE = ROOT / "config" / "mode_choice.json"

MODE_ORDER = ("drive", "bike", "walk", "pt_walk", "pt_bike")
NO_PATH_TIME_MIN = 999.0
ASP_START = "17:00"
ASP_END = "18:00"
GTFS_SERVICE_DATE = "2026-04-23"

WALK_SPEED_KPH = 5.0
BIKE_SPEED_CITY_KPH = 13.0
BIKE_SPEED_CANTON_KPH = 13.0
MAX_WALK_DISTANCE_KM = 5.0

DRIVE_OCCUPANCY = 1.14
EXTERNAL_BACKGROUND_CITY_FACTOR = 0.10
EXTERNAL_BACKGROUND_CANTON_FACTOR = 0.20
ASSIGNMENT_MAX_ITERATIONS = 50
ASSIGNMENT_MIN_ITERATIONS = 10
ASSIGNMENT_STALL_ITERATIONS = 25
ASSIGNMENT_RELATIVE_GAP = 0.01
ASSIGNMENT_OD_THRESHOLD = 0.01

# Per-end connector penalties and parking/terminal times are perceived times.
DRIVE_CONNECTOR_CITY_MIN = 12.0
DRIVE_CONNECTOR_CANTON_MIN = 1.0
CAR_TERMINAL_CITY_MIN = 5.0
CAR_TERMINAL_CANTON_MIN = 2.0
DRIVE_INTRAZONAL_MIN = 5.0
PT_INTRAZONAL_MIN = 5.0
PT_ACCESS_FLOOR_MIN = 2.0
PT_EGRESS_FLOOR_MIN = 2.0
PT_TRANSFER_PHYSICAL_FLOOR_MIN = 1.0

DEFAULT_EBIKE_SHARE = 0.25
EBIKE_SPEED_MULTIPLIER = 1.5
